isim=str(input("Adınızı giriniz: "))
cinsiyet=str(input("Cinsiyetinizi giriniz: "))
yas=int(input("Yaşınızı giriniz: "))
boy=float(input("Boyunuzu metre cinsinden giriniz: "))
kilo=float(input("Kilonuzu giriniz: "))
print(" Adınız: {}\nCinsiyetiniz: {}\nYaşınız: {}\nBoyunuz: {}\nKilonuz: {}".format(isim,cinsiyet,yas,boy,kilo))
print("a'nın tipi:",type(isim))
print("b'nın tipi:",type(cinsiyet))
print("c'nın tipi:",type(yas))
print("d'nın tipi:",type(boy))
print("e'nın tipi:",type(kilo))